# Generated by Django 5.2.5 on 2025-08-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_desc_contact_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Anonymous', max_length=70),
        ),
    ]
